### ISSUE TITLE
When i launch it，i got a '403' feedback

### ISSUE THREAD

**Issue by WangElsie** [poumason/DotblogsSampleCode#12]
My Subscription-Key is right and i got the accessToken。
But when i launch it，i got a '403' feedback
Are there anyother reasons for it。

**Comment by poumason** [comment]
Hi, 
Which project can not be run?

**Comment by WangElsie** [comment]
15-AudioRecordSample, I use debug when run at
 `ar response = await client.PostAsync(new Uri(uri), streamContent)`
I got the status is‘403’

**Comment by WangElsie** [comment]
My Key is `**d5096397c30a4fad8efbb3a6676db185**`

**Comment by poumason** [comment]
Because the Speech REST API change the URL, you can reference the link: https://docs.microsoft.com/en-us/azure/cognitive-services/speech/getstarted/getstartedrest?tabs=Powershell

I will modify the sample to support new API format.

**Comment by poumason** [comment]
Done
